#!/usr/bin/env bash

if ! gpg --list-keys &> /dev/null; then
    gpg --full-generate-key
else
    echo "GPG key already exist"
fi

if [[ ! -e ~/.ssh/id_ed25519 ]]; then
    ssh-keygen -t ed25519
    ssh-keygen -c -f ~/.ssh/id_ed25519
    ssh-keygen -l -f ~/.ssh/id_ed25519
    cat ~/.ssh/id_ed25519.pub
else
    echo "SSH key already exist"
fi
