#!/usr/bin/env bash

pip install --user virtualenvwrapper

if true; then
    # needed by pyperclip, dependency of xonsh's vim mode
    sudo apt install xsel

    echo "installing xonsh"
    ~/.local/bin/pipx install 'xonsh[full]'

    echo "Installing xontribs"
    ~/.local/pipx/venvs/xonsh/bin/python -m pip install \
        xontrib-argcomplete \
        xontrib-avox \
        xontrib-avox-poetry \
        xontrib-hist-navigator \
        xontrib-kitty \
        xontrib-term-integrations

    WANT_SHELL=/home/lieryan/.local/bin/xonsh
else
    echo "installing zsh"
    sudo apt install zsh python3-pip

    WANT_SHELL=/usr/bin/zsh
fi

if [ "$(getent passwd $USER | cut -d ':' -f 7)" != $WANT_SHELL ]; then
    echo "changing shell to $WANT_SHELL"
    chsh -s $WANT_SHELL
fi
