#!/usr/bin/env bash

pip install --user virtualenvwrapper

if true; then
    echo "installing xonsh"
    ~/.local/bin/pipx install 'xonsh[full]'

    ~/.local/pipx/venvs/xonsh/bin/python -m pip install xontrib-avox xontrib-avox-poetry

    WANT_SHELL=/home/lieryan/.local/bin/xonsh
else
    echo "installing zsh"
    sudo apt install zsh python3-pip

    WANT_SHELL=/usr/bin/zsh
fi

if [ "$(getent passwd $USER | cut -d ':' -f 7)" != $WANT_SHELL ]; then
    echo "changing shell to $WANT_SHELL"
    chsh -s $WANT_SHELL
fi
