#!/usr/bin/env bash

sudo apt install \
    --no-install-recommends \
    jupyter-qtconsole \
    python3-pip \
    python3-venv

pip install --user \
    virtualenvwrapper \
    pipx

python3 -m pipx ensurepath

python3 -m pipx install cookiecutter 
python3 -m pipx install poetry
python3 -m pipx install pre-commit
